project_id = "hbwkufaksipsqipqdqcv"

[functions.analyze-work-patterns]
verify_jwt = true

[functions.consolidate-duplicate-accounts]
verify_jwt = true

[functions.calculate-time-segments]
verify_jwt = true

[functions.migrate-historical-timesheets]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.update-employee-username]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.update-user-role]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reprocess-missing-segments]
verify_jwt = true

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.cleanup-invalid-entries]
verify_jwt = true

[functions.process-approved-vacation]
verify_jwt = true

[functions.withdraw-approved-vacation]
verify_jwt = true

[functions.process-approved-medical-leave]
verify_jwt = true

[functions.withdraw-approved-medical-leave]
verify_jwt = true

[functions.test-schedule-notifications]
verify_jwt = true
