project_id = "hbwkufaksipsqipqdqcv"

[functions.calculate-time-segments]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.bulk-create-users]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true