project_id = "hbwkufaksipsqipqdqcv"

[functions.calculate-time-segments]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.bulk-create-users]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.update-employee-username]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.gdpr-delete-user-data]
verify_jwt = true

[functions.gdpr-export-user-data]
verify_jwt = true

[functions.cleanup-old-data]
verify_jwt = false

[functions.check-password-strength]
verify_jwt = false

[functions.check-rate-limit]
verify_jwt = false
