// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { iosStorage } from '@/lib/iosStorage';

const SUPABASE_URL = "https://wxatbftfzkeodcfyevfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4YXRiZnRmemtlb2RjZnlldmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNDkyNjUsImV4cCI6MjA3NjYyNTI2NX0.S7_ViCdGly1x7BR6HM7L-t7f8u3PBVHGorEHSQM6GkU";

// Custom storage adapter pentru iOS PWA compatibility
const storageAdapter = {
  getItem: async (key: string) => {
    return await iosStorage.getItem(key);
  },
  setItem: async (key: string, value: string) => {
    await iosStorage.setItem(key, value);
  },
  removeItem: async (key: string) => {
    await iosStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});